### ISSUE TITLE
Improve how to compile guide

### ISSUE THREAD

**Issue by ZechariahB** [urFate/QAdwaitaPlatform#3]
Feature request! Currently, the guide for compiling this library is rather small. It should be a good idea to add extra information such as which dependencies are required for successful compilation and add examples on how to compile it for both qt5 and qt6 so that it can be easier for others to get started trying it out.

**Comment by urFate** [comment]
Added [step-by-step guide ](https://github.com/urFate/QAdwaitaPlatform/commit/20ae53db4a90a57ce384882853dfb0186516dd29)& [dependencies list](https://github.com/urFate/QAdwaitaPlatform/commit/a824ba4bff480a0c78e949b8d2b17abc022a6d75) to README.
