### ISSUE TITLE
qBitTorrent still looking like GTK3

### ISSUE THREAD

**Issue by emansom** [urFate/QAdwaitaPlatform#6]
**Describe the bug**
When running qBitTorrent on an Arch system with the AUR package [`qadwaitaplatform-git`](https://aur.archlinux.org/pkgbase/qadwaitaplatform-git) installed, nothing changes much compared to the regular version of QGnomePlatform.

**To Reproduce**
1. Install the AUR package [`qadwaitaplatform-git`](https://aur.archlinux.org/pkgbase/qadwaitaplatform-git).
2. Launch qBittorrent in a terminal with the environment variable `QT_QPA_PLATFORMTHEME=gnome` set (or e.g. configured user-wide using [`environment.d`](https://man.archlinux.org/man/environment.d.5.en))
3. Observe most buttons still and other UI elements still looking like old GTK3.

**Expected behavior**
QAdwaitaPlatform transforming qBitTorrent to a nice and clean looking adwaita themed app.

**Screenshots**
![Schermafdruk van 2023-07-16 10-33-25](https://github.com/urFate/QAdwaitaPlatform/assets/981494/0c47acc4-6c9d-43f9-8aa4-f1c6e44fd325)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: latest git

**Comment by urFate** [comment]
QAdwaitaPlatform and QGnomePlatform change only the title bar theme of the window and not the application itself. For the LibAdwaita-style application themes, I recommend using [the KvLibAdwaita](https://github.com/GabePoel/KvLibadwaita) theme (it is also used in the demo screenshots) for [the Kvantum](https://archlinux.org/packages/extra/x86_64/kvantum/) theme engine.
